version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: gift-casamento-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gift_list
      POSTGRES_PASSWORD: gift_list
      POSTGRES_DB: gift_casamento_dev
    ports:
      - "5432:5432"
    volumes:
      - gift_casamento_pg_data:/var/lib/postgresql/data

volumes:
  gift_casamento_pg_data:
